# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72a7a953fa157d671deb160275e53fef06c55732d1db9b958df48d53d868c67af1271755e202c9942ffa7f3fe6fcb6fb01d9c8d12adab7c8dfc6475c9c2e88a9

test:
  secret_key_base: e4d243a0f88f4c0b8ef3c922ca03a2de2b8c52a8ba9128bdbfeecfc286934c7f4299f8236ee5f3d0d632f3e63897d5f1b2b507ba2c054820a887c8af68d8ba60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
